/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package featureboard.java.sdk;

//TODO: clean me up
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
