name: Build & Test CI
concurrency: main
env:
  CI: true

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.version.outputs.changes }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@featureboard'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Disable verify-store-integrity
        run: |
          pnpm set verify-store-integrity false

      - name: pnpm install
        run: |
          pnpm install

      - name: Version command
        id: version
        run: |
          npx changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          pnpm i -r --no-frozen-lockfile
          git config user.email "jake@featureboard.app"
          git config user.name "Jake Ginnivan"
          git add -A
          git commit -m "Version packages [skip ci]" || echo "No changes to commit"
          git push

      - name: Type check
        run: pnpm tsc -b

      - name: Lint types and code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Package libs
        run: pnpm package

      - name: Release packages
        run: pnpm publish -r --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
