name: PR Workflow
env:
  CI: true

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: |
          pnpm set verify-store-integrity false

      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm tsc -b

      - name: Lint types and code
        run: pnpm run lint

      - name: Tests
        run: pnpm run test
